name: Sync HotTrend

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Call Sync HotTrend API
        env:
          GLOBAL_API_KEY: ${{ secrets.GLOBAL_API_KEY }}
        run: |
          curl -X GET "https://artimind.top/api/cronTask/hotTrends" -H "x-api-key: $GLOBAL_API_KEY"
